language: python
python:
  - "3.6"
script: coverage run harbor/tests.py
before_install:
  pip install codecov coverage
after_success:
  codecov --token=
notifications:
    slack: girard-assistant:WJNGB4w80siM7XhTnzO2ECMZ
